### ISSUE TITLE
NTP_OFFSET how to adjust the Time Zones

### ISSUE THREAD

**Issue by ghost** [jptrsn/clock-message-board#1]
actually i m playing around with this really good stuff but i can t change the time zone.

**Comment by jptrsn** [comment]
Time zones are defined according to the [time zone library](https://github.com/JChristensen/Timezone), so you can refer to that documentation for more detailed information.

For the quick version, take a look at the lines in the sketch that determine the time change rules. That's where you define the offset from GMT. For example, in the following two lines, daylight time is defined as -240 minutes offset, and standard time is defined as -300 minutes offset.

```
TimeChangeRule myDST = {"EDT", Second, Sun, Mar, 2, -240};    //Daylight time = UTC - 4 hours
TimeChangeRule mySTD = {"EST", First, Sun, Nov, 2, -300};     //Standard time = UTC - 5 hours
```

**Comment by ghost** [comment]
works perfect. thanks
