### ISSUE TITLE
switch OFF Clock

### ISSUE THREAD

**Issue by ghost** [jptrsn/clock-message-board#2]
Hi actually i wan to switch of the permanent time. is that possible?
Br Dave

**Comment by jptrsn** [comment]
That's not something I've implemented, but I welcome a pull request with a modification to allow the functionality.

For clarity, you'd like to have the display be "off" (e.g. no pixels illuminated at all) until a message is received and displayed?

**Comment by ghost** [comment]
yes it would be great to switch off all pixels, i show you a picture ob my display. it is a bit different from yours. if all pixels are of it looks like a piece of wood

**Comment by ghost** [comment]
![IMG_20191222_111738](https://user-images.githubusercontent.com/35889916/71323219-0c384300-24d1-11ea-82aa-6fde225d1ad9.jpg)

**Comment by ghost** [comment]
i can t do the pull request, it doesn t work :-(
