### ISSUE TITLE
Memory Leak or a bug?

### ISSUE THREAD

**Issue by skalavala** [jptrsn/clock-message-board#3]
First of all, thank you so much for the code. I was able to set it up and run in no time! 

I think there is some sort of memory leak or a bug in the code  - especially when using MQTT. I have a script that drops a message to MQTT topic `messageboard/messages` every 30 seconds. The message is not very long, something like "55 degrees outside, It is going to be sunny or the next hour!". The message changes based on hourly forecast from a weather api.

After running for a few hours, I noticed that it stopped showing time and the messages, and started showing random garbage {pixels}, never recovers and ultimately turns off completely.

**Update 1: I tried for another day without dropping any messages to MQTT, and it works fine. If someone wants to re-create the bug, all you have to do is drop a message in MQTT every 30 seconds and run it for a few hours.**

**Update 2: I removed all the references to ArduinoJSON, and the issue went away. I no longer use the text effects...etc as I am pretty happy with default scrolling behavior. It could be that the json libraries may have memory leaks...**

Does anyone notice this?

**Comment by jptrsn** [comment]
Thanks for posting the updates, you've made more progress understanding the issue than I have.

I've noticed that the problem occurs when receiving an MQTT message during a parola transition. That is, if the MQTT topic publishes while the minute is rolling over, it will cause the bug to appear.

I'll use what you've discovered and see if I can improve the code. Thanks again!

**Comment by skalavala** [comment]
I trust that you fix the bug. I am going to go ahead and close the issue. 

**Once again, thank you so much for taking time to look into it!**
